# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    resolvers:
        default:
            web_path: ~

    # your filter sets are defined here
    filter_sets:

        # use the default cache configuration
        cache: ~

        # the name of the "filter set"
        sample_image:

            quality: 80

                # list of transformations to apply (the "filters")
            filters:
                thumbnail: { size: [ 680 , 800 ], mode: outbound }

                # create a thumbnail: set size to 120x90 and use the "outbound" mode
                # to crop the image when the size ratio of the input differs
                downscale:

                    # input 3960x2560px -> output 1980x1280px
                    max: [ 1080 , 1350 ]
