vich_uploader:
    db_driver: orm

    mappings:
        sample_images:
            uri_prefix: '%app.path.sample_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.sample_images%'
        application_images:
            uri_prefix: '%app.path.application_images%'
            upload_destination: '%kernel.project_dir%/public%app.path.application_images%'
