# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.path.sample_images: /uploads/images/samples
    app.path.application_images: /uploads/images/applications

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\EventSubscriber\LocaleSubscriber:
        arguments: [ '%kernel.default_locale%' ]

    app.menu_builder:
        class: App\Menu\MenuBuilder
        arguments: [ "@knp_menu.factory" ]
        tags:
            - { name: knp_menu.menu_builder, method: createMainMenu, alias: main }
            - { name: knp_menu.menu_builder, method: createSidebarMenu, alias: sidebar }
            - { name: knp_menu.menu_builder, method: createLoginMenu, alias: login }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    admin.menu:
        class: App\Admin\MenuAdmin
        arguments: [ ~, App\Entity\Menu, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Menu }
    admin.system_form:
        class: App\Admin\SystemFormAdmin
        arguments: [~, App\Entity\SystemForm,~]
        tags:
            - {name: sonata.admin, manager_type: orm, label: System Forms}
    admin.profile_setting:
        class: App\Admin\ProfileSettingAdmin
        arguments: [ ~, App\Entity\ProfileSetting,~ ]
        tags:
          - { name: sonata.admin, manager_type: orm, label: Profile Settings }
    admin.menu_entries:
        class: App\Admin\MenuEntryAdmin
        arguments: [ ~, App\Entity\MenuEntry, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Menu Entries }
    admin.user:
        class: App\Admin\UserAdmin
        arguments: [ ~, App\Entity\User, ~,'@security.password_hasher' ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: User }
    admin.sample_images:
        class: App\Admin\SampleImageAdmin
        arguments: [ ~, App\Entity\SampleImage, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Sample Images }
    admin.sample_comments:
        class: App\Admin\SampleCommentAdmin
        arguments: [ ~, App\Entity\SampleComment, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Sample Comments }
    admin.tags:
        class: App\Admin\TagAdmin
        arguments: [ ~, App\Entity\Tag, ~ ]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Tags }
